### ISSUE TITLE
Windows build broken

### ISSUE THREAD

**Issue by agargara** [dartmouth-cs98/Quantum-Tetris#253]
The current Windows build at quantumtetris.com gives me the error message:

"Could not open game data at path '.'. Is the .pck file missing?"

![image](https://user-images.githubusercontent.com/658381/76277762-f74b9e80-62cc-11ea-95c9-b550f7e1b350.png)

**Comment by yash1848** [comment]
The Godot Package is not provided with the exe. It also has to be uploaded. Generate it in Godot:
![Annotation 2020-03-10 153029](https://user-images.githubusercontent.com/62011132/76301466-4a7d1b80-62e4-11ea-8bd7-08f05dbcd267.png)

**Comment by Trevor-Dartmouth** [comment]
The windows version should now work thanks so much for the help!
